### PR TITLE
clone melpa with https

### PR DESCRIPTION
**Pull request by steckerhalter**

### CODE REVIEW

**Comment by deepfire** [comment]
@steckerhalter: works for me, thanks!

**Comment by steckerhalter** [comment]
@wasamasa can you have a look at this too?

**Comment by wasamasa** [comment]
Looks fine to me.  I'm not sure why you're defaulting to HTTPS though, considering that you're changing a default and the case of a corporate firewall ought to be the exception, not the norm.

**Comment by steckerhalter** [comment]
it's not just because of the firewall, https is secure, git proto is insecure, that's why I wanted to change it in the first place

**Comment by steckerhalter** [comment]
so to me it looks like the code from `package-build` does not really checkout the latest changes when updating since it does:

    git remote update

which only updates origin. Am I missing something?

**Comment by steckerhalter** [comment]
So after having considered the potential problems with relying on so many `package-build` internals I went back to using just `package-build--checkout-git` for now.

I'll try to address the shallow clone option with melpa directly

**Pull request merged**
