### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by steckerhalter**

### CODE REVIEW

**Comment by kiennq** [comment]
Thanks, can you also fix the `discover-my-major` repo is not found issue in travis too?

**Comment by steckerhalter** [comment]
yeah, done :smile: 
it works now. wanna change something. otherwise I guess you could merge

**Comment by steckerhalter** [comment]
oh, I thought I'll re-add the badge. stay tuned.

**Comment by kiennq** [comment]
Merge

**Comment by steckerhalter** [comment]
:ok_hand:

**Pull request merged**
