### PR TITLE
refactor cache update into function

### PR DESCRIPTION
**Pull request by steckerhalter**
tried to clean up the `quelpa` function a bit, hopefully everything still works. can you check? thx

### CODE REVIEW

**Comment by wasamasa** [comment]
It still works, but this muddles up cache changes with the installation step, so I'd break down that part (or just leave it as is).

**Comment by steckerhalter** [comment]
it's just another helper function. what do you mean by muddle up?

**Comment by steckerhalter** [comment]
ah now I see, you mean `(quelpa-package-install arg)`. right, that's not very good

**Comment by steckerhalter** [comment]
now it's better but it could still be made cleaner if all arguments would just be parsed in one place.
`rcp` seems to have been unused so I removed that

**Comment by steckerhalter** [comment]
the shadowing business **does** make it a bit dangerous so that would another thing we could get rid off (as you suggested once)

**Comment by wasamasa** [comment]
Right, that would be the next thing I'd touch, simply to make the relationship between argument passing and enabled features more explicit.

**Comment by steckerhalter** [comment]
I think package-build should also be upgraded if quelpa is, hence I added that. Imagine the scenario: package-build makes some breaking change, we update quelpa, people get the updated quelpa but not the updated package-build -> we break all the things

In this context we could probably also drop `quelpa-checkout-melpa` since updating package-build does that and remove the variable `quelpa-update-melpa-p`?

**Comment by steckerhalter** [comment]
I might revert this again since if package-build is having breaking changes there is really no way for us to fix it. If we update package-build first then quelpa will not work anymore and vice-versa

**Comment by steckerhalter** [comment]
@wasamasa can you merge if ok? I removed the last commit that changed the behavior of quelpa-self-upgrade. I think now it makes the code at least a bit more readable.

**Comment by wasamasa** [comment]
OK, let's keep the shadowing for another pull request.

**Pull request merged**
