### PR TITLE
remove not needed pb code

### PR DESCRIPTION
**Pull request by steckerhalter**

### CODE REVIEW

**Comment by steckerhalter** [comment]
@wasamasa Can you have a look if there's more code we can get rid of?

**Comment by wasamasa** [comment]
FWIW, I don't really see any reason to delete code. It will make syncing to the next major release needlessly hard.

**Comment by steckerhalter** [comment]
pretty much everything changed anyway, so syncing is not getting any harder. but it's better to have only what we use of the old code.

**Comment by steckerhalter** [comment]
I'm not even sure if syncing is desirable since I'd like to keep the fetchers. Migrating to the new code base would be a lot of work and then the dependency on upstream just randomly breaks quelpa as it already did more than once.

**Comment by steckerhalter** [comment]
well, anyway, it's not a big deal to add code later, but we really don't need badges, json and package archive code etc.

**Pull request merged**
