### PR TITLE
Implement suggestion from #69

### PR DESCRIPTION
**Pull request by wasamasa**
This change tries removing existing recipes, then adds the installed one.

### CODE REVIEW

**Comment by steckerhalter** [comment]
is cl-remove removing all occurrences or just one?

**Comment by steckerhalter** [comment]
what do you think about if we would sort the cache alphabetically? for `quelpa-upgrade` this would help so you would have a better idea about the progress

**Comment by wasamasa** [comment]
`cl-remove` goes for all occurrences. Sorting the cache might make sense, I just wonder at which time to do it.

**Comment by steckerhalter** [comment]
just after new values have been pushed?

**Comment by steckerhalter** [comment]
works well.

I think somehow we should also remove entries from the cache where the package is not installed anymore. I delete many packages via the package manager but they are still in the cache. So if I run `quelpa-upgrade` then they are installed again when I obviously don't want them any longer.

I guess that could be done before sorting the cache, testing with `package-installed-p`

**Comment by steckerhalter** [comment]
or maybe this should be done when `quelpa-upgrade` is run, which would make more sense

**Comment by wasamasa** [comment]
The latter sounds better because it would keep the logic where it should be instead of burdening the `quelpa` function any further.

**Comment by steckerhalter** [comment]
I added a line that should do it...

**Comment by wasamasa** [comment]
Right, I totally forgot about the special keyword arguments of `cl-lib` functions.

**Comment by steckerhalter** [comment]
Do you think we can merge it? Wouldn't want to break something...

**Comment by wasamasa** [comment]
This requires at least a test of the new functionality before it can be merged.

**Comment by wasamasa** [comment]
Do you have an idea how exactly a test of this would look like? The CI script does the building, but no actual checks (other than aborting the test on a failed installation) whereas the test file checks up whether a few core functions work. Mocking an installation for the purpose of checking whether the cache works correctly sounds tedious.

**Comment by steckerhalter** [comment]
yeah, I think that sounds (and looks) fine

**Comment by wasamasa** [comment]
Cool, I'll merge that then and take a look at the other open stuff depending on this.

**Pull request merged**
