### PR TITLE
Update the repo of recipes on `quelpa-upgrade` or `quelpa-self-upgrade`.

### PR DESCRIPTION
**Pull request by jaccarmac**
The documentation for `quelpa-update-melpa-p` indicates that when nil certain
interactive commands will update the MELPA repo, but this is not the case. This
commit fixes that problem by making the checkout function take a parameter
instead of reading a dynamic variable. This means the setup function maintains
its checkout behavior with regards to `quelpa-update-melpa-p` but the two
commands mentioned above will always do an update. Notably, this update occurs
only once, even though `quelpa-upgrade` calls `quelpa-self-upgrade`.

### CODE REVIEW

**Comment by steckerhalter** [comment]
> The documentation for quelpa-update-melpa-p indicates that when nil certain
interactive commands will update the MELPA repo, but this is not the case. 

actually when `nil` it should not do anything with the melpa repo

**Comment by jaccarmac** [comment]
https://github.com/quelpa/quelpa/blob/c095fa14046c1313b97df4ec102bdea5a981ff1d/quelpa.el#L131-L133

According to the existing documentation `quelpa-upgrade` and `quelpa-self-upgrade` should still update the MELPA repo. If this is not the case I can reconfigure the pull request to fix that docstring and add an interactive command to update the recipes repository.

**Comment by steckerhalter** [comment]
You're right. That probably never worked as advertised. I think to change the docstring and add an interactive function would be better then since otherwise we change the current behavior. Thanks

**Comment by jaccarmac** [comment]
You're welcome, and thank you for the clarification!

**Pull request closed without merging**
