### PR TITLE
melpa fetcher:  more firewall friendliness: git -> https

### PR DESCRIPTION
**Pull request by deepfire**

### CODE REVIEW

**Comment by steckerhalter** [comment]
hi thanks for the PR. I have just recently benchmarked this change and found that clone with https is approx. twice the time than git proto. since melpa keeps piling up git history and is already very large this would slow down quelpa setup quite a bit.

maybe melpa could be shallow cloned then this would be ok

**Comment by deepfire** [comment]
@steckerhalter, currently it just blocks indefinitely in your average corporate environment..

**Comment by syl20bnr** [comment]
I was about to name a PR to address this but I planed to add a configuration variable for this.

I cannot install fully Spacemacs at work without patching both quelpa and build-package.el which is anyone ;-)

**Comment by deepfire** [comment]
Maybe it should be a defcustom..

**Comment by steckerhalter** [comment]
Shallow clone (`--depth 50` for example)and a switch to https would probably be the best solution. Someone just needs to update `quelpa-checkout-melpa` not to use `package-build--checkout-git` (git options cannot be specified) :)

**Comment by steckerhalter** [comment]
I copy pasted the code from `package-build` and added `--depth 50` in #89 

Can you test as well?

**Comment by deepfire** [comment]
In fifteen minutes..

**Comment by deepfire** [comment]
It works for me.

**Comment by steckerhalter** [comment]
changed to https  and added custom in #89

**Comment by steckerhalter** [comment]
The default has been changed in `package-build` as well now, see: https://github.com/milkypostman/melpa/blob/master/package-build.el#L529

**Pull request closed without merging**
